# Generated by Django 3.0.8 on 2021-06-13 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third')], default=1)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finished'],
            },
        ),
        migrations.CreateModel(
            name='VoteVariant_Type3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('FR', 'First'), ('SC', 'Second'), ('TH', 'Third')], default='FR', max_length=2)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='VoteVariant_Type2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('FR', 'First'), ('SC', 'Second'), ('TH', 'Third')], default='FR', max_length=2)),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.Voting')),
            ],
        ),
        migrations.CreateModel(
            name='VoteVariant_Type1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('voting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votings.Voting')),
            ],
        ),
    ]
